name: Build and deploy Node.js app to Azure Web App - avicsc

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CI: false
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test -- --passWithNoTests

      - name: Archive build output
        run: |
          mkdir -p archive
          zip -r ./archive/node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-archive
          path: ./archive/node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-archive
          path: ./archive

      - name: Extract artifact
        run: |
          mkdir -p build
          unzip ./archive/node-app.zip -d ./build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CD39DAABEA114FCBB93463C1C4EE3C17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_982630B329D447099D097E9A6DB127BF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA2D4770323441848A924609E225CB99 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'avicsc'
          slot-name: 'Production'
          package: ./build
